timezone: Asia/Tokyo
encoding: UTF-8
show_drafts: false

title: ねねボタン
email: nenebutton [at] gmail [dot] com ([at]と[dot]は適切に置き換えてください)
description: >- # this means to ignore newlines until "baseurl:"
  桃鈴ねねさんの非公式ファンサイトです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mozune-api
github_username:  mozune-api
repository: mozune-api/mozune-api.github.io

# Build settings
theme: - 
plugins:
  - jekyll-feed
